--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.63.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 1/12/2018 7:00:55 PM
-- Server version: 5.7.20-log
-- Client version: 4.1
--


--
-- Definition for database androidtesting
--
DROP DATABASE IF EXISTS androidtesting;
CREATE DATABASE IF NOT EXISTS androidtesting
	CHARACTER SET utf8
	COLLATE utf8_general_ci;

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE androidtesting;

--
-- Definition for table donor
--
CREATE TABLE IF NOT EXISTS donor (
  DonorID INT(11) NOT NULL,
  DName VARCHAR(20) DEFAULT NULL,
  BloodGroup VARCHAR(10) DEFAULT NULL,
  MobileNo VARCHAR(20) DEFAULT NULL,
  Age INT(11) DEFAULT NULL,
  City VARCHAR(30) DEFAULT NULL,
  Address VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (DonorID)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table donor
--
INSERT INTO donor VALUES
(1, 'Anwar', 'A+', '03131234567', 29, 'Dera Ismail Khan', 'House#123, Street#2, DIK'),
(2, 'Zohaib', 'B+', '03135984567', 25, 'Lahore', 'House#231, Street#5, LHR'),
(3, 'Mehran', 'O-', '03451234512', 21, 'Islamabad', 'House#258, Street#9, ISB'),
(4, 'Imran', 'AB-', '03001239874', 26, 'Jaranwala', 'House#437, Street#3, JRW'),
(5, 'Irfan', 'O+', '03099874563', 20, 'Sargodha', 'House#111, Street#11, SRG');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;